CREATE TABLE IF NOT EXISTS `mysqlmigrate` (
    `id` CHAR(100) NOT NULL,
    `file` CHAR(50) NOT NULL,
    `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`, `file`)
) ENGINE=InnoDB;
